baseURL: "https://akshayy-dev.netlify.app"
languageCode: en-us
title: Akshay Dev
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      # weight: 10
    - # identifier: blog
      # name: Blog
      # url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Akshay Dev"
    subtitle: "Incoming [**MEng Civil**](https://civmin.utoronto.ca/home/programs/graduate-programs/meng/) student at the **University of Toronto**. I'm passionate about **Intelligent Trnasportation Systems**, **Transport Planning** and **Pavement Engineering**. Before joining the MEng program, I worked as a **Traffic Engineer** at [**ITSPE Pvt Ltd**](https://www.itspe.co.in/), a company specialising in Intelligent Transport Systems (ITS) based in India."
    imageUrl: "home/akpic.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:akshay.dev@mail.utoronto.ca"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/akshaybdev/"
    - name: "github"
      url: "https://github.com/AkshayyDev"
#    - name: "facebook"
#      url: "https://www.youtube.com/c/"
    - name: "instagram"
      url: "https://instagram.com/akshayy.dev?igshid=NTc4MTIwNjQ2YQ=="
#    - #name: "cv"
#      #url: "https://drive.google.com/file/d/1U6Gg2RnHSCthtWLbZJ"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
